package com.dengagefintech.demo.push

import android.content.Context
import android.content.Intent
import android.content.IntentFilter
import androidx.core.content.ContextCompat
import com.dengage.sdk.push.NRTrampoline
import com.dengagefintech.demo.Events
import com.dengagefintech.demo.Screen
import org.json.JSONArray
import org.json.JSONObject

/* ============================================================================
   THE NOVAPAY PUSH GALLERY

   Every push capability Dengage offers, rendered on this device with NovaPay's
   own copy and artwork, and no network involved.

   HOW IT WORKS, AND WHY IT IS NOT A MOCK. It hands the SDK's own receiving path
   the same intent a real payload produces, carrying the keys a real payload
   carries. What appears on screen is drawn by the Dengage SDK, from a Dengage
   payload, in every respect except that the bytes were assembled here rather
   than arriving over FCM. Calling the receiver directly is deliberate. Do not
   route this through Dengage.onMessageReceived: required for correct behaviour
   with this SDK version. Background: ask Salil.

   The earlier version of this file built four NotificationCompat notifications
   by hand. That proved Android could draw a notification, which was never in
   question, and proved nothing about how the SDK parses a payload, resolves a
   target URL, reads custom parameters or honours an expiry. Those are the parts
   a prospect is actually evaluating, so the gallery now goes through the SDK.

   WHAT IT PROVES, AND WHAT IT DOES NOT. It proves how every format renders and
   how this app handles it: tap routing, deep links, custom parameters, inbox
   copies, action buttons. It does not prove DELIVERY, because nothing was
   delivered, and it does not prove SERVER-SIDE PERSONALISATION, because there
   is no server here to resolve a tag. Both need a real send. The personalised
   rows carry the resolved OUTPUT plus the exact tag to paste into the panel,
   so the same thing can be proven properly in one send.

   The Test Area says LOCAL on this whole card for that reason: a locally built
   payload that looks right has caused wrong conclusions on this project before.

   Payload keys and JSON shapes match what this SDK version reads. Keep them
   exactly as written.
   ========================================================================== */
object NovaPayPushGallery {

    /* 1024x512, which BigPictureStyle downsamples comfortably. Generated by
       tools/assets/pushart.js and committed: a demo must not depend on a third
       party image host, and PNG rather than SVG because a notification image is
       decoded as a bitmap. */
    private const val IMG = "https://salil-dengage.github.io/dengage-demos/fintech/images/push"

    /**
     * @param panelTag when set, the Advanced Personalization to paste into the
     *        panel's Title or Message to reproduce this row on a real send.
     *        Shown on screen, because a local render cannot resolve a tag.
     */
    data class Format(
        val key: String,
        val label: String,
        val note: String,
        val panelTag: String? = null,
    )

    val FORMATS: List<Format> = listOf(
        // ----------------------------------------------------------- formats
        Format("text", "Text only",
            "Title and message. The everyday one."),
        Format("subtext", "Subtext, emoji, badge and sound",
            "Every Android option on one notification: subtext, an emoji, a badge count, a sound."),
        Format("rich", "Rich, with an image",
            "Expands to a full width image. Pull it down."),
        Format("buttons", "Rich with action buttons",
            "Two buttons that settle a card query without opening the app."),
        Format("carousel", "Carousel, three cards",
            "Swipe through three offers inside the notification."),

        // -------------------------------------------------------- behaviours
        Format("deeplink", "Deep link to Grow",
            "Opens the Grow screen, not the app's front door."),
        Format("params", "Custom parameters",
            "Carries data the customer never sees. screen=grow even overrides the target URL."),
        Format("inbox", "Also saved to App Inbox",
            "Carries addToInbox. The copy needs a real send: the inbox is read from the server."),
        Format("silent", "Silent, draws nothing",
            "No banner, by design. Writes an engagement row instead."),
        Format("expiring", "With an expiry",
            "A fee free week that has closed should not resurface."),

        // ------------------------------------------------------ personalised
        Format("perso_name", "Personalised by name",
            "Resolved output shown here; Dengage fills the tag at send time.",
            panelTag = "Good morning, {%= \$Contact.first_name %}"),
        Format("perso_fallback", "Personalised, with a fallback",
            "The same message for a contact with no name, which is the case that embarrasses a demo.",
            panelTag = "{% if (\$Contact.first_name) { %}Good morning, " +
                "{%= \$Contact.first_name %}{% } else { %}Good morning{% } %}"),
        Format("perso_data", "Personalised from your data",
            "A balance and a date from the contact, formatted server side.",
            panelTag = "Your balance is {%= \$Contact.balance %} as of " +
                "{%= FormatDate(\$Contact.statement_date, 'dd MMM') %}"),
    )

    /**
     * Renders one row on this device.
     *
     * @return a line fit to show on screen. Silent correctly produces nothing
     *         visible, and the line is where that gets said.
     */
    fun show(context: Context, key: String): String {
        app = context.applicationContext
        return render(key)
    }

    private var app: Context? = null

    private fun render(key: String): String = when (key) {

        "text" -> {
            post(
                title = "Your pay has landed",
                message = "3,200.00 from Acme Corp payroll. Move some before the month does.",
                targetUrl = screen(Screen.MONEY),
            )
            "Drew the text notification."
        }

        "subtext" -> {
            post(
                title = "Fee free week ends Friday 🌍",
                message = "Send money in any currency this week with no transfer fee.",
                subTitle = "Transfers",
                targetUrl = screen(Screen.SEND_MONEY),
                badgeCount = 3,
            )
            "Drew it with subtext, an emoji, a badge of 3 and the default sound."
        }

        "rich" -> {
            post(
                title = "Spending abroad this month",
                message = "The Travel plan converts at the real rate with no markup.",
                targetUrl = screen(Screen.PRODUCTS),
                mediaUrl = "$IMG/travel.png",
                type = "RICH",
            )
            "Drew the rich notification. Expand it to see the image."
        }

        "buttons" -> {
            post(
                title = "Card used in Lisbon",
                message = "A payment of 42.10 EUR was authorised on your Plus card.",
                targetUrl = screen(Screen.CARDS),
                mediaUrl = "$IMG/travel.png",
                type = "RICH",
                buttons = listOf(
                    "That was me" to screen(Screen.CARDS),
                    "Freeze card" to screen(Screen.CARDS),
                ),
            )
            "Drew it with two action buttons."
        }

        "carousel" -> {
            post(
                title = "Three things your plan could do",
                message = "Swipe to see which one suits how you actually spend.",
                targetUrl = screen(Screen.PRODUCTS),
                type = "CAROUSEL",
            )
            "Drew the carousel. Expand it and use Back and Next."
        }

        "deeplink" -> {
            post(
                title = "Japan 2027 is nearly funded",
                message = "A little more and the goal is reached.",
                targetUrl = screen(Screen.GROW),
                mediaUrl = "$IMG/payday.png",
                type = "RICH",
            )
            "Drew it. Tapping it opens Grow, not the front door."
        }

        "params" -> {
            post(
                title = "Your July statement is ready",
                message = "Tap it, then read the parameters on the IDs screen.",
                targetUrl = screen(Screen.MONEY),
                customParams = listOf(
                    "account_id" to "NPY-CUR-001",
                    "statement_period" to "2026-07",
                    "screen" to Screen.GROW,
                ),
            )
            "Drew it with three parameters. screen=grow overrides the target URL, " +
                "so it opens Grow rather than Money."
        }

        "inbox" -> {
            post(
                title = "Your pay day summary",
                message = "Kept in your inbox so you can come back to it.",
                targetUrl = screen(Screen.INBOX),
                mediaUrl = "$IMG/payday.png",
                type = "RICH",
                addToInbox = true,
            )
            "Drew it carrying addToInbox. The copy will NOT appear in App Inbox " +
                "from here: the inbox is read from the server, and this push never " +
                "reached the server. Only a real send fills it."
        }

        "silent" -> {
            /* Deliberately not routed through the renderer: a silent push draws
               nothing, so rendering it would demonstrate an absence. The row is
               the observable part, and writing it is what the real silent
               handler does. */
            Events.engagement("silent_push_received", mapOf(
                "channel" to "push",
                "widget_name" to "silent_push",
                "interaction" to "triggered"
            ))
            "Nothing drawn, which is correct. Wrote an engagement row with " +
                "widget_name = silent_push instead. Check the Events screen."
        }

        "expiring" -> {
            post(
                title = "Fee free week closes at midnight",
                message = "After that the offer is gone, and so is this message.",
                targetUrl = screen(Screen.SEND_MONEY),
                /* Already past, so the SDK's expiry check has something real to
                   act on rather than a date that never arrives. */
                expireDate = "2026-08-01 23:59:59",
            )
            "Sent one already past its expiry. A push that no longer applies " +
                "should not resurface."
        }

        "perso_name" -> {
            post(
                title = "Good morning, Elena",
                message = "Round ups moved 47.20 into Japan 2027 last month.",
                targetUrl = screen(Screen.GROW),
            )
            "Drew the RESOLVED output. Dengage fills the tag at send time; paste " +
                "the tag shown above into the panel to prove it end to end."
        }

        "perso_fallback" -> {
            post(
                title = "Good morning",
                message = "Round ups moved 47.20 into Japan 2027 last month.",
                targetUrl = screen(Screen.GROW),
            )
            "The same message for a contact with no first name. No dangling " +
                "comma, no \"Hello ,\". This is the case worth showing."
        }

        "perso_data" -> {
            post(
                title = "Your July statement is ready",
                message = "Your balance is 2,480.00 USD as of 01 Aug.",
                targetUrl = screen(Screen.MONEY),
                customParams = listOf("account_id" to "NPY-CUR-001"),
            )
            "Balance and date resolved from the contact. FormatDate does the " +
                "formatting server side, so the app never parses a date string."
        }

        else -> "Unknown format."
    }

    // -------------------------------------------------------------- content --

    private fun screen(name: String) = "novapay://$name"

    // -------------------------------------------------------------- payload --

    /* The map mirrors what FCM delivers. Keep the key names exactly as
       written. */
    private fun post(
        title: String,
        message: String,
        targetUrl: String,
        subTitle: String? = null,
        mediaUrl: String? = null,
        type: String = "TEXT",
        buttons: List<Pair<String, String>> = emptyList(),
        customParams: List<Pair<String, String>> = emptyList(),
        addToInbox: Boolean = false,
        badgeCount: Int? = null,
        expireDate: String? = null,
    ) {
        val data = HashMap<String, String>()
        data["messageSource"] = "DENGAGE"
        /* A distinct id per push, so each is its own notification rather than
           replacing the last. */
        data["messageId"] = (System.currentTimeMillis() % 100_000).toString()
        data["title"] = title
        data["message"] = message
        data["targetUrl"] = targetUrl
        data["notificationType"] = type
        data["sound"] = "default"
        data["dengageCampName"] = "NovaPay gallery"
        subTitle?.let { data["subTitle"] = it }
        mediaUrl?.let { data["mediaUrl"] = it }
        expireDate?.let { data["expireDate"] = it }
        if (addToInbox) data["addToInbox"] = "true"
        badgeCount?.let { data["badge"] = "true"; data["badgeCount"] = it.toString() }

        if (buttons.isNotEmpty()) {
            data["actionButtons"] = JSONArray().apply {
                buttons.forEachIndexed { i, (text, url) ->
                    put(JSONObject().apply {
                        put("id", "npy-btn-$i")
                        put("text", text)
                        put("targetUrl", url)
                        put("icon", "")
                    })
                }
            }.toString()
        }

        if (customParams.isNotEmpty()) {
            data["customParams"] = JSONArray().apply {
                customParams.forEach { (k, v) ->
                    put(JSONObject().put("key", k).put("value", v))
                }
            }.toString()
        }

        /* A locally drawn push never passes through the FCM service, so without
           this the "Last push received" card stays empty and the custom
           parameters have nowhere to appear.

           It deliberately does NOT touch unreadInbox. That counter is the
           PLATFORM saying it filed a message, and nothing here reached the
           platform, so moving the badge from a local push would make the one
           honest signal on the inbox screen a lie. */
        NovaPayFcmService.lastPush = data

        deliver(data)
    }

    /* The last step a real push takes before it becomes a notification: the
       payload, the parsing and the rendering are all the SDK's; only the
       transport is skipped. Calling the receiver directly rather than
       broadcasting is deliberate, see the note at the top of this file. */
    private val trampoline = NRTrampoline()

    private fun deliver(data: HashMap<String, String>) {
        val context = app ?: return

        /* The same single exception NovaPayFcmService makes: this app draws the
           carousel format itself, from local vector artwork. Routed through the
           same renderer a real send uses, so the gallery row shows what a
           campaign shows rather than a second implementation that could drift. */
        if (NovaPayCarousel.handles(data)) {
            val drawn = NovaPayCarousel.show(context, 0)
            if (!drawn.startsWith("carousel failed")) return
        }

        ensureClickReceiver(context)
        val intent = Intent(ACTION_RECEIVE).apply {
            setPackage(context.packageName)
            /* A fresh request code on every push, so two notifications cannot
               share a PendingIntent, which would make the second one open the
               first one's target. */
            putExtra("requestCode", (System.nanoTime() and 0x3FFFFFFF).toInt())
            data.forEach { (k, v) -> putExtra(k, v) }
        }
        trampoline.onReceive(context, intent)
    }

    /* ONE receiver, registered once per process, and the filter carries exactly
       ACTION_CLICK, ITEM_CLICK and CAROUSEL_ITEM_CLICK, nothing more. Do not add
       RECEIVE to this filter: NovaPayApp keeps a single live receiver for that
       action and adding it here would supersede the SDK's own. Required for
       correct behaviour with this SDK version. Background: ask Salil. */
    @Volatile private var clickReceiverRegistered = false

    private fun ensureClickReceiver(context: Context) {
        if (clickReceiverRegistered) return
        clickReceiverRegistered = true
        val filter = IntentFilter(ACTION_ACTION_CLICK).apply {
            addAction(ACTION_ITEM_CLICK)
            addAction(ACTION_CAROUSEL_ITEM_CLICK)
        }
        runCatching {
            ContextCompat.registerReceiver(
                context, trampoline, filter, ContextCompat.RECEIVER_NOT_EXPORTED
            )
        }
    }

    private const val ACTION_RECEIVE = "com.dengage.push.intent.RECEIVE"
    private const val ACTION_ACTION_CLICK = "com.dengage.push.intent.ACTION_CLICK"
    private const val ACTION_ITEM_CLICK = "com.dengage.push.intent.ITEM_CLICK"
    private const val ACTION_CAROUSEL_ITEM_CLICK = "com.dengage.push.intent.CAROUSEL_ITEM_CLICK"
}
